from typing import Any, Dict, Literal, Optional

from ..shared.schema import DenoiseSpec, TimeframeLiteral
from ..utils.barriers import normalize_trade_direction as _normalize_trade_direction
from . import barriers_optimization as _barriers_optimization
from . import barriers_probabilities as _barriers_probabilities
from .barriers_shared import (
    BARRIER_GRID_PRESETS,
    DEGENERATE_OBJECTIVE_MIN_RESOLVE,
    PHANTOM_PROFIT_LOSS_THRESHOLD,
    PHANTOM_PROFIT_NO_HIT_THRESHOLD,
    _auto_barrier_method,
    _brownian_bridge_hits,
    _is_crypto_symbol,
)


def forecast_barrier_hit_probabilities(
    symbol: str,
    timeframe: TimeframeLiteral = "H1",
    horizon: int = 12,
    method: Literal["mc_gbm", "mc_gbm_bb", "hmm_mc", "garch", "bootstrap", "heston", "jump_diffusion", "auto"] = "hmm_mc",
    direction: Literal["long", "short"] = "long",
    tp_abs: Optional[float] = None,
    sl_abs: Optional[float] = None,
    tp_pct: Optional[float] = None,
    sl_pct: Optional[float] = None,
    tp_pips: Optional[float] = None,
    sl_pips: Optional[float] = None,
    params: Optional[Dict[str, Any]] = None,
    denoise: Optional[DenoiseSpec] = None,
) -> Dict[str, Any]:
    return _barriers_probabilities.forecast_barrier_hit_probabilities(
        symbol=symbol,
        timeframe=timeframe,
        horizon=horizon,
        method=method,
        direction=direction,
        tp_abs=tp_abs,
        sl_abs=sl_abs,
        tp_pct=tp_pct,
        sl_pct=sl_pct,
        tp_pips=tp_pips,
        sl_pips=sl_pips,
        params=params,
        denoise=denoise,
    )


def forecast_barrier_closed_form(
    symbol: str,
    timeframe: TimeframeLiteral = "H1",
    horizon: int = 12,
    direction: Literal["long", "short"] = "long",
    barrier: float = 0.0,
    mu: Optional[float] = None,
    sigma: Optional[float] = None,
    denoise: Optional[DenoiseSpec] = None,
) -> Dict[str, Any]:
    return _barriers_probabilities.forecast_barrier_closed_form(
        symbol=symbol,
        timeframe=timeframe,
        horizon=horizon,
        direction=direction,
        barrier=barrier,
        mu=mu,
        sigma=sigma,
        denoise=denoise,
    )


def forecast_barrier_optimize(
    symbol: str,
    timeframe: TimeframeLiteral = "H1",
    horizon: int = 12,
    method: Literal["mc_gbm", "mc_gbm_bb", "hmm_mc", "garch", "bootstrap", "heston", "jump_diffusion", "auto"] = "hmm_mc",
    direction: Literal["long", "short"] = "long",
    mode: Literal["pct", "pips"] = "pct",
    tp_min: float = 0.25,
    tp_max: float = 1.5,
    tp_steps: int = 7,
    sl_min: float = 0.25,
    sl_max: float = 2.5,
    sl_steps: int = 9,
    params: Optional[Dict[str, Any]] = None,
    denoise: Optional[DenoiseSpec] = None,
    objective: Literal[
        "edge",
        "prob_tp_first",
        "prob_resolve",
        "kelly",
        "kelly_cond",
        "ev",
        "ev_cond",
        "ev_per_bar",
        "profit_factor",
        "min_loss_prob",
        "utility",
    ] = "ev",
    return_grid: bool = True,
    top_k: Optional[int] = None,
    output: Literal["full", "summary"] = "full",
    viable_only: bool = False,
    concise: bool = False,
    grid_style: Literal["fixed", "volatility", "ratio", "preset"] = "fixed",
    preset: Optional[str] = None,
    vol_window: int = 250,
    vol_min_mult: float = 0.5,
    vol_max_mult: float = 4.0,
    vol_steps: int = 7,
    vol_sl_extra: float = 1.8,
    vol_floor_pct: float = 0.15,
    vol_floor_pips: float = 8.0,
    ratio_min: float = 0.5,
    ratio_max: float = 4.0,
    ratio_steps: int = 8,
    refine: bool = False,
    refine_radius: float = 0.3,
    refine_steps: int = 5,
    min_prob_win: Optional[float] = None,
    max_prob_no_hit: Optional[float] = None,
    max_median_time: Optional[float] = None,
    fast_defaults: bool = False,
    search_profile: Literal["fast", "medium", "long"] = "medium",
    statistical_robustness: bool = False,
    target_ci_width: float = 0.05,
    n_seeds_stability: int = 3,
    enable_bootstrap: bool = False,
    n_bootstrap: int = 200,
    enable_convergence_check: bool = True,
    convergence_window: int = 100,
    convergence_threshold: float = 0.01,
    enable_power_analysis: bool = False,
    power_effect_size: float = 0.05,
    enable_sensitivity_analysis: bool = False,
    sensitivity_params: Optional[list] = None,
) -> Dict[str, Any]:
    return _barriers_optimization.forecast_barrier_optimize(
        symbol=symbol,
        timeframe=timeframe,
        horizon=horizon,
        method=method,
        direction=direction,
        mode=mode,
        tp_min=tp_min,
        tp_max=tp_max,
        tp_steps=tp_steps,
        sl_min=sl_min,
        sl_max=sl_max,
        sl_steps=sl_steps,
        params=params,
        denoise=denoise,
        objective=objective,
        return_grid=return_grid,
        top_k=top_k,
        output=output,
        viable_only=viable_only,
        concise=concise,
        grid_style=grid_style,
        preset=preset,
        vol_window=vol_window,
        vol_min_mult=vol_min_mult,
        vol_max_mult=vol_max_mult,
        vol_steps=vol_steps,
        vol_sl_extra=vol_sl_extra,
        vol_floor_pct=vol_floor_pct,
        vol_floor_pips=vol_floor_pips,
        ratio_min=ratio_min,
        ratio_max=ratio_max,
        ratio_steps=ratio_steps,
        refine=refine,
        refine_radius=refine_radius,
        refine_steps=refine_steps,
        min_prob_win=min_prob_win,
        max_prob_no_hit=max_prob_no_hit,
        max_median_time=max_median_time,
        fast_defaults=fast_defaults,
        search_profile=search_profile,
        statistical_robustness=statistical_robustness,
        target_ci_width=target_ci_width,
        n_seeds_stability=n_seeds_stability,
        enable_bootstrap=enable_bootstrap,
        n_bootstrap=n_bootstrap,
        enable_convergence_check=enable_convergence_check,
        convergence_window=convergence_window,
        convergence_threshold=convergence_threshold,
        enable_power_analysis=enable_power_analysis,
        power_effect_size=power_effect_size,
        enable_sensitivity_analysis=enable_sensitivity_analysis,
        sensitivity_params=sensitivity_params,
    )


__all__ = [
    "BARRIER_GRID_PRESETS",
    "DEGENERATE_OBJECTIVE_MIN_RESOLVE",
    "PHANTOM_PROFIT_LOSS_THRESHOLD",
    "PHANTOM_PROFIT_NO_HIT_THRESHOLD",
    "_auto_barrier_method",
    "_brownian_bridge_hits",
    "_is_crypto_symbol",
    "_normalize_trade_direction",
    "forecast_barrier_closed_form",
    "forecast_barrier_hit_probabilities",
    "forecast_barrier_optimize",
]
