from typing import Any, Dict, Optional, Literal

from ..core.schema import TimeframeLiteral, DenoiseSpec
from .common import fetch_history as _fetch_history, log_returns_from_prices as _log_returns_from_prices
from ..utils.utils import parse_kv_or_json as _parse_kv_or_json
from ..utils.barriers import (
    get_pip_size as _get_pip_size,
    resolve_barrier_prices as _resolve_barrier_prices,
    normalize_trade_direction as _normalize_trade_direction,
    barrier_prices_are_valid as _barrier_prices_are_valid,
)
from .monte_carlo import (
    simulate_gbm_mc as _simulate_gbm_mc,
    simulate_hmm_mc as _simulate_hmm_mc,
    simulate_garch_mc as _simulate_garch_mc,
    simulate_bootstrap_mc as _simulate_bootstrap_mc,
    simulate_heston_mc as _simulate_heston_mc,
    simulate_jump_diffusion_mc as _simulate_jump_diffusion_mc,
    gbm_single_barrier_upcross_prob as _gbm_upcross_prob,
)
from . import barriers_probabilities as _barriers_probabilities
from . import barriers_optimization as _barriers_optimization
from . import barriers_shared as _barriers_shared
from .barriers_shared import (
    BARRIER_GRID_PRESETS,
    DEGENERATE_OBJECTIVE_MIN_RESOLVE,
    PHANTOM_PROFIT_LOSS_THRESHOLD,
    PHANTOM_PROFIT_NO_HIT_THRESHOLD,
    _annotate_candidate_metrics,
    _auto_barrier_method,
    _binomial_se,
    _binomial_wilson_95,
    _brownian_bridge_hits,
    _build_selection_diagnostics,
    _candidate_is_viable,
    _candidate_status_reason,
    _get_live_reference_price,
    _is_crypto_symbol,
    _least_negative_ref,
    _safe_float,
    _scale_price_paths_to_reference,
    _sort_candidate_results,
)


def _sync_barrier_dependencies() -> None:
    sync_map = {
        "_fetch_history": _fetch_history,
        "_log_returns_from_prices": _log_returns_from_prices,
        "_parse_kv_or_json": _parse_kv_or_json,
        "_get_pip_size": _get_pip_size,
        "_resolve_barrier_prices": _resolve_barrier_prices,
        "_normalize_trade_direction": _normalize_trade_direction,
        "_barrier_prices_are_valid": _barrier_prices_are_valid,
        "_simulate_gbm_mc": _simulate_gbm_mc,
        "_simulate_hmm_mc": _simulate_hmm_mc,
        "_simulate_garch_mc": _simulate_garch_mc,
        "_simulate_bootstrap_mc": _simulate_bootstrap_mc,
        "_simulate_heston_mc": _simulate_heston_mc,
        "_simulate_jump_diffusion_mc": _simulate_jump_diffusion_mc,
        "_gbm_upcross_prob": _gbm_upcross_prob,
        "_auto_barrier_method": _auto_barrier_method,
        "_binomial_se": _binomial_se,
        "_binomial_wilson_95": _binomial_wilson_95,
        "_brownian_bridge_hits": _brownian_bridge_hits,
        "_build_selection_diagnostics": _build_selection_diagnostics,
        "_candidate_is_viable": _candidate_is_viable,
        "_candidate_status_reason": _candidate_status_reason,
        "_get_live_reference_price": _get_live_reference_price,
        "_is_crypto_symbol": _is_crypto_symbol,
        "_least_negative_ref": _least_negative_ref,
        "_safe_float": _safe_float,
        "_scale_price_paths_to_reference": _scale_price_paths_to_reference,
        "_sort_candidate_results": _sort_candidate_results,
        "_annotate_candidate_metrics": _annotate_candidate_metrics,
        "BARRIER_GRID_PRESETS": BARRIER_GRID_PRESETS,
        "DEGENERATE_OBJECTIVE_MIN_RESOLVE": DEGENERATE_OBJECTIVE_MIN_RESOLVE,
        "PHANTOM_PROFIT_NO_HIT_THRESHOLD": PHANTOM_PROFIT_NO_HIT_THRESHOLD,
        "PHANTOM_PROFIT_LOSS_THRESHOLD": PHANTOM_PROFIT_LOSS_THRESHOLD,
    }
    for module in (_barriers_shared, _barriers_probabilities, _barriers_optimization):
        for name, value in sync_map.items():
            setattr(module, name, value)


def forecast_barrier_hit_probabilities(
    symbol: str,
    timeframe: TimeframeLiteral = "H1",
    horizon: int = 12,
    method: Literal['mc_gbm', 'mc_gbm_bb', 'hmm_mc', 'garch', 'bootstrap', 'heston', 'jump_diffusion', 'auto'] = 'hmm_mc',
    direction: Literal['long', 'short'] = 'long',
    tp_abs: Optional[float] = None,
    sl_abs: Optional[float] = None,
    tp_pct: Optional[float] = None,
    sl_pct: Optional[float] = None,
    tp_pips: Optional[float] = None,
    sl_pips: Optional[float] = None,
    params: Optional[Dict[str, Any]] = None,
    denoise: Optional[DenoiseSpec] = None,
) -> Dict[str, Any]:
    _sync_barrier_dependencies()
    return _barriers_probabilities.forecast_barrier_hit_probabilities(
        symbol=symbol,
        timeframe=timeframe,
        horizon=horizon,
        method=method,
        direction=direction,
        tp_abs=tp_abs,
        sl_abs=sl_abs,
        tp_pct=tp_pct,
        sl_pct=sl_pct,
        tp_pips=tp_pips,
        sl_pips=sl_pips,
        params=params,
        denoise=denoise,
    )


def forecast_barrier_closed_form(
    symbol: str,
    timeframe: TimeframeLiteral = "H1",
    horizon: int = 12,
    direction: Literal['long', 'short'] = 'long',
    barrier: float = 0.0,
    mu: Optional[float] = None,
    sigma: Optional[float] = None,
    denoise: Optional[DenoiseSpec] = None,
) -> Dict[str, Any]:
    _sync_barrier_dependencies()
    return _barriers_probabilities.forecast_barrier_closed_form(
        symbol=symbol,
        timeframe=timeframe,
        horizon=horizon,
        direction=direction,
        barrier=barrier,
        mu=mu,
        sigma=sigma,
        denoise=denoise,
    )


def forecast_barrier_optimize(
    symbol: str,
    timeframe: TimeframeLiteral = "H1",
    horizon: int = 12,
    method: Literal['mc_gbm', 'mc_gbm_bb', 'hmm_mc', 'garch', 'bootstrap', 'heston', 'jump_diffusion', 'auto'] = 'hmm_mc',
    direction: Literal['long', 'short'] = 'long',
    mode: Literal['pct', 'pips'] = 'pct',
    tp_min: float = 0.25,
    tp_max: float = 1.5,
    tp_steps: int = 7,
    sl_min: float = 0.25,
    sl_max: float = 2.5,
    sl_steps: int = 9,
    params: Optional[Dict[str, Any]] = None,
    denoise: Optional[DenoiseSpec] = None,
    objective: Literal['edge', 'prob_tp_first', 'prob_resolve', 'kelly', 'kelly_cond', 'ev', 'ev_cond', 'ev_per_bar', 'profit_factor', 'min_loss_prob', 'utility'] = 'ev',
    return_grid: bool = True,
    top_k: Optional[int] = None,
    output: Literal['full', 'summary'] = 'full',
    viable_only: bool = False,
    concise: bool = False,
    grid_style: Literal['fixed', 'volatility', 'ratio', 'preset'] = 'fixed',
    preset: Optional[str] = None,
    vol_window: int = 250,
    vol_min_mult: float = 0.5,
    vol_max_mult: float = 4.0,
    vol_steps: int = 7,
    vol_sl_extra: float = 1.8,
    vol_floor_pct: float = 0.15,
    vol_floor_pips: float = 8.0,
    ratio_min: float = 0.5,
    ratio_max: float = 4.0,
    ratio_steps: int = 8,
    refine: bool = False,
    refine_radius: float = 0.3,
    refine_steps: int = 5,
    min_prob_win: Optional[float] = None,
    max_prob_no_hit: Optional[float] = None,
    max_median_time: Optional[float] = None,
    fast_defaults: bool = False,
    search_profile: Literal['fast', 'medium', 'long'] = 'medium',
) -> Dict[str, Any]:
    _sync_barrier_dependencies()
    return _barriers_optimization.forecast_barrier_optimize(
        symbol=symbol,
        timeframe=timeframe,
        horizon=horizon,
        method=method,
        direction=direction,
        mode=mode,
        tp_min=tp_min,
        tp_max=tp_max,
        tp_steps=tp_steps,
        sl_min=sl_min,
        sl_max=sl_max,
        sl_steps=sl_steps,
        params=params,
        denoise=denoise,
        objective=objective,
        return_grid=return_grid,
        top_k=top_k,
        output=output,
        viable_only=viable_only,
        concise=concise,
        grid_style=grid_style,
        preset=preset,
        vol_window=vol_window,
        vol_min_mult=vol_min_mult,
        vol_max_mult=vol_max_mult,
        vol_steps=vol_steps,
        vol_sl_extra=vol_sl_extra,
        vol_floor_pct=vol_floor_pct,
        vol_floor_pips=vol_floor_pips,
        ratio_min=ratio_min,
        ratio_max=ratio_max,
        ratio_steps=ratio_steps,
        refine=refine,
        refine_radius=refine_radius,
        refine_steps=refine_steps,
        min_prob_win=min_prob_win,
        max_prob_no_hit=max_prob_no_hit,
        max_median_time=max_median_time,
        fast_defaults=fast_defaults,
        search_profile=search_profile,
    )
